// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    data: function(_options) {
      return '';
    },
    meta: function(arg) {
      var date;
      date = arg.date;
      return {
        pubdate: date.format(),
        title: '',
        tags: [''],
        minutes: 0
      };
    }
  };

}).call(this);
