// Generated by CoffeeScript 1.10.0
(function() {
  var templates, weekday, weekend;

  weekday = require('./template-weekday');

  weekend = require('./template-weekend');

  templates = {
    "default": weekday,
    weekday: weekday,
    weekend: weekend
  };

  module.exports = function(id) {
    return templates[id];
  };

}).call(this);
