// Generated by CoffeeScript 1.10.0
(function() {
  var fs, getBaseNamePath, getMetaFile, getTitle, moment, path, readMeta;

  fs = require('fs-extra');

  path = require('path');

  moment = require('moment');

  getBaseNamePath = function(dir, date) {
    var _, m, ref, y;
    ref = date.split('-'), y = ref[0], m = ref[1], _ = ref[2];
    return path.join(dir, y, m, date);
  };

  getMetaFile = function(dir, date) {
    return getBaseNamePath(dir, date) + '.json';
  };

  getTitle = function(dir, date) {
    return readMeta(getMetaFile(dir, date)).title;
  };

  readMeta = function(file) {
    var data;
    data = fs.readFileSync(file, {
      encoding: 'utf8'
    });
    return JSON.parse(data);
  };

  module.exports = {
    data: function(arg) {
      var directory, m, posts;
      m = arg.date, directory = arg.directory;
      posts = [1, 2, 3, 4, 5, 6, 7].map(function(i) {
        return moment(m).subtract(i, 'days').format('YYYY-MM-DD');
      }).map(function(date) {
        return {
          date: date,
          title: getTitle(directory, date),
          url: "http://blog.bouzuya.net/" + (date.replace(/-/g, '/')) + "/"
        };
      });
      return "# 今週のふりかえり\n\n" + (posts.map(function(i) {
        return "- [" + i.date + " " + i.title + "][" + i.date + "]";
      }).join('\n'));
    },
    meta: function(arg) {
      var date;
      date = arg.date;
      return {
        pubdate: date.format(),
        title: '',
        tags: [''],
        minutes: 0
      };
    }
  };

}).call(this);
